# Generated by Django 4.2.6 on 2023-11-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0014_alter_watermark_image'),
        ('blog', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_photos', to='photologue.photoeffect'),
        ),
    ]
