# Generated by Django 4.2.6 on 2023-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_gallery_galleryphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='effect',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(through='blog.GalleryPhoto', to='blog.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
